name: myconda
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - celery
  - gevent
  - xarray
  - cnmaps
  - cartopy
  - geopandas
  - scikit-learn
  - statsmodels
  - xeofs
  - pycwt
  - pandas
  - numpy
  - openpyxl
  - sqlalchemy
  - psycopg2
  - sshtunnel
  - metpy
  - simplejson
  - tqdm
  - docxtpl
  - docxcompose
  - pykrige
  - pip:
    - nmc-met-io
    - redis
    - gunicorn
    - supervisor
    - gma
    - emd-signal
